const FETCH_CITIES = 'FETCH_CITIES';
const FETCH_REPORT_DATA = 'FETCH_REPORT_DATA';
const SET_FROM_DATE = 'SET_FROM_DATE';
const SET_UNTIL_DATE = 'SET_UNTIL_DATE';
const SET_CURRENT_CITY = 'SET_CURRENT_CITY';

export default {
  FETCH_CITIES,
  FETCH_REPORT_DATA,
  SET_FROM_DATE,
  SET_UNTIL_DATE,
  SET_CURRENT_CITY,
}